.DEFAULT_GOAL := help

.PHONY: help test race vet build-cross verify

help:
	@printf '%s\n' \
	  'make verify  Run the mandatory correctness gate for every source change.'

verify: test race vet build-cross

test:
	go test ./...

race:
	go test -race ./...

vet:
	go vet ./...

build-cross:
	GOOS=linux GOARCH=amd64 go build ./...
	GOOS=linux GOARCH=arm64 go build ./...
	GOOS=linux GOARCH=386 go build ./...
	GOOS=linux GOARCH=riscv64 go build ./...
	GOOS=js GOARCH=wasm go build ./...
